--INV
GRANT CONNECT TO INV;
GRANT CREATE SESSION TO INV;
GRANT CREATE TABLE TO INV;
GRANT CREATE PROCEDURE TO INV;
GRANT CREATE SEQUENCE TO INV;
GRANT CREATE SYNONYM TO INV;
GRANT CREATE TRIGGER TO INV;
GRANT CREATE TYPE TO INV;
GRANT CREATE VIEW TO INV;
GRANT CREATE MATERIALIZED VIEW TO INV;
GRANT CREATE PUBLIC SYNONYM TO INV;
GRANT DEBUG ANY PROCEDURE TO INV;
GRANT DROP PUBLIC SYNONYM TO INV;

--Admin
GRANT CONNECT TO admin;
GRANT CREATE SESSION TO admin;
GRANT CREATE TRIGGER TO admin;

--AR
GRANT CONNECT TO AP;
GRANT CREATE SESSION TO AP;
GRANT CREATE TABLE TO AP;
GRANT CREATE PROCEDURE TO AP;
GRANT CREATE SEQUENCE TO AP;
GRANT CREATE SYNONYM TO AP;
GRANT CREATE TRIGGER TO AP;
GRANT CREATE TYPE TO AP;
GRANT CREATE VIEW TO AP;
GRANT CREATE MATERIALIZED VIEW TO AP;
GRANT CREATE PUBLIC SYNONYM TO AP;
GRANT DEBUG ANY PROCEDURE TO AP;
GRANT DROP PUBLIC SYNONYM TO AP;