CREATE OR REPLACE TRIGGER logon_trg 
  AFTER LOGON ON DATABASE
BEGIN
    IF (user = 'INV') THEN
      EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = INV';
    ELSIF (user = 'ADMIN') THEN
      EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ADMIN';  
    ELSIF (user = 'AP') THEN
      EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = AP';      
    end if;
EXCEPTION 
  WHEN OTHERS 
    THEN NULL; -- prevent a login failure due to an exception
END logon_trg;
/  